server:
  port: 8080

spring:
  datasource:
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.129:3306/heima_travel?useSSL=false
mybatis:
  type-aliases-package: com.heima.travel.pojo
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql #pagehelper???? mybatis
  reasonable: true #???<=0 ????????????>=?????????????
  supportMethodsArguments: true # ?????? Mapper ??????????????????
  params: count=countSql